package com.egov.entity;

public enum Category {
    AGRICULTURE,
    EDUCATION,
    HEALTH,
    EMPLOYMENT,
    INFRASTRUCTURE,
    WOMEN_EMPOWERMENT,
    CHILD_WELFARE,
    SENIOR_CITIZEN,
    HOUSING,
    SOCIAL_WELFARE,
    ENVIRONMENT,
    RURAL_DEVELOPMENT,
    URBAN_DEVELOPMENT,
    FINANCIAL_INCLUSION,
    SKILL_DEVELOPMENT,
    TRANSPORT,
    TOURISM,
    TECHNOLOGY,
}